[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo    = 'Shougo/neosnippet-snippets'
depends = ['Shougo/neosnippet']

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
